version: '3'

services:
    postgres:
        container_name: ${POSTGRES_NAME}
        image: postgres:11
        restart: unless-stopped
        volumes:
            - postgres-data:/data
        environment:
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        networks:
            - app-connect
        ports:
            - '${POSTGRES_PORT}:5432'

    mongo:
        container_name: ${MONGO_NAME}
        image: mongo
        restart: unless-stopped
        networks:
            - app-connect
        ports:
            - '${MONGO_PORT}:27017'

volumes:
    postgres-data:

networks:
    app-connect:
        driver: bridge
